from typing import TypedDict

from langgraph.graph import StateGraph, START, END

from agents.supervisor_agent import supervisor_agent
from agents.retrieval_agent import retrieval_agent
from agents.analysis_agent import analysis_agent
from agents.sql_agent import sql_agent
from agents.web_agent import web_agent
from agents.validation_agent import validation_agent


class RAGState(TypedDict):

    question: str
    route: str

    context: str

    answer: str

    validation: str

    retry_count: int


def supervisor_node(state: RAGState):

    question = state["question"]

    route = supervisor_agent(
        question
    )

    return {
        "route": route
    }


def retrieval_node(state: RAGState):

    question = state["question"]

    result = retrieval_agent(
        question
    )

    context = result.get(
        "context",
        ""
    )

    return {
        "context": context
    }


def sql_node(state: RAGState):

    question = state["question"]

    answer = sql_agent(
        question
    )

    return {
        "answer": answer
    }


def web_node(state: RAGState):

    question = state["question"]

    answer = web_agent(
        question
    )

    return {
        "answer": answer
    }


def analysis_node(state: RAGState):

    question = state["question"]

    context = state["context"]

    answer = analysis_agent(
        question=question,
        context=context
    )

    return {
        "answer": answer
    }


def validation_node(state: RAGState):

    question = state["question"]

    answer = state["answer"]

    route = state["route"]

    context = state.get(
        "context",
        ""
    )

    evidence = context

    if route == "SQL":

        evidence = (
            "The answer was generated by the "
            "SQL Agent using the connected "
            "SQL Server database."
        )

    elif route == "WEB":

        evidence = (
            "The answer was generated by the "
            "Web Research Agent using current "
            "web search results."
        )

    validation = validation_agent(
        question=question,
        answer=answer,
        evidence=evidence
    )

    return {
        "validation": validation
    }


def route_question(state: RAGState):

    route = state["route"]

    if route == "RAG":
        return "rag"

    if route == "SQL":
        return "sql"

    if route == "WEB":
        return "web"

    return "rag"


def route_validation(state: RAGState):

    validation = state.get(
        "validation",
        "INVALID"
    )

    retry_count = state.get(
        "retry_count",
        0
    )

    if validation == "VALID":

        return "valid"

    if retry_count >= 1:

        return "valid"

    return "retry"


def retry_node(state: RAGState):

    retry_count = state.get(
        "retry_count",
        0
    )

    return {
        "retry_count": retry_count + 1
    }


def create_rag_graph():

    graph = StateGraph(
        RAGState
    )

    # -----------------------------
    # Nodes
    # -----------------------------

    graph.add_node(
        "supervisor",
        supervisor_node
    )

    graph.add_node(
        "retrieval_agent",
        retrieval_node
    )

    graph.add_node(
        "sql_agent",
        sql_node
    )

    graph.add_node(
        "web_agent",
        web_node
    )

    graph.add_node(
        "analysis_agent",
        analysis_node
    )

    graph.add_node(
        "validation_agent",
        validation_node
    )

    graph.add_node(
        "retry",
        retry_node
    )

    # -----------------------------
    # Start
    # -----------------------------

    graph.add_edge(
        START,
        "supervisor"
    )

    # -----------------------------
    # Supervisor routing
    # -----------------------------

    graph.add_conditional_edges(
        "supervisor",
        route_question,
        {
            "rag": "retrieval_agent",
            "sql": "sql_agent",
            "web": "web_agent",
        }
    )

    # -----------------------------
    # RAG path
    # -----------------------------

    graph.add_edge(
        "retrieval_agent",
        "analysis_agent"
    )

    graph.add_edge(
        "analysis_agent",
        "validation_agent"
    )

    # -----------------------------
    # SQL path
    # -----------------------------

    graph.add_edge(
        "sql_agent",
        "validation_agent"
    )

    # -----------------------------
    # Web path
    # -----------------------------

    graph.add_edge(
        "web_agent",
        "validation_agent"
    )

    # -----------------------------
    # Validation
    # -----------------------------

    graph.add_conditional_edges(
        "validation_agent",
        route_validation,
        {
            "valid": END,
            "retry": "retry",
        }
    )

    # -----------------------------
    # Retry
    # -----------------------------

    graph.add_edge(
        "retry",
        "supervisor"
    )

    return graph.compile()